### ISSUE TITLE
env变量不生效

### ISSUE THREAD

**Issue by dnslin** [Alice39s/kuma-mieru#78]
FEATURE_EDIT_THIS_PAGE=false
FEATURE_SHOW_STAR_BUTTON=false

不生效 

docker部署，chrome浏览器 清除了缓存

```yaml

services:
  kuma-mieru:
    # image: ghcr.io/alice39s/kuma-mieru:latest # 还在测试中，建议 build 安装
    # image: kuma-mieru
    build: .
    container_name: kuma-mieru
    restart: unless-stopped
    ports:
      - "3883:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - UPTIME_KUMA_BASE_URL=${UPTIME_KUMA_BASE_URL}
      - PAGE_ID=${PAGE_ID}
      - FEATURE_EDIT_THIS_PAGE=${FEATURE_EDIT_THIS_PAGE}
      - FEATURE_SHOW_STAR_BUTTON=${FEATURE_SHOW_STAR_BUTTON}
      - FEATURE_TITLE=${FEATURE_TITLE}
      - FEATURE_DESCRIPTION=${FEATURE_DESCRIPTION}
      - FEATURE_ICON=${FEATURE_ICON}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    tmpfs:
      - /tmp


```
```dockerfile
FROM oven/bun:1.2-alpine AS builder
WORKDIR /app

# 使用阿里云 APK 源
ARG ALPINE_MIRROR=https://mirrors.aliyun.com
RUN sed -i "s|dl-cdn.alpinelinux.org|${ALPINE_MIRROR#https://}|g" /etc/apk/repositories \
    && apk update \
    && apk add --no-cache curl

# 设置中国 NPM 镜像
ENV NPM_CONFIG_REGISTRY=https://registry.npmmirror.com

# 环境变量
ARG NODE_ENV=production
ARG NEXT_TELEMETRY_DISABLED=1
ARG UPTIME_KUMA_BASE_URL=https://xxx.xx
ARG PAGE_ID=dnslin
ARG FEATURE_EDIT_THIS_PAGE=false
ARG FEATURE_SHOW_STAR_BUTTON=false
ARG FEATURE_TITLE="xxxx"
ARG FEATURE_DESCRIPTION="A beautiful and modern uptime monitoring dashboard"
ARG FEATURE_FEATURE_ICON=
ARG IS_DOCKER=true

ENV NODE_ENV=${NODE_ENV} \
    NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED} \
    UPTIME_KUMA_BASE_URL=${UPTIME_KUMA_BASE_URL} \
    PAGE_ID=${PAGE_ID} \
    FEATURE_EDIT_THIS_PAGE=${FEATURE_EDIT_THIS_PAGE} \
    FEATURE_SHOW_STAR_BUTTON=${FEATURE_SHOW_STAR_BUTTON} \
    FEATURE_TITLE=${FEATURE_TITLE} \
    FEATURE_DESCRIPTION=${FEATURE_DESCRIPTION} \
    FEATURE_FEATURE_ICON=${FEATURE_FEATURE_ICON}

RUN if [ "$UPTIME_KUMA_BASE_URL" = "https://whimsical-sopapillas-78abba.netlify.app" ]; then \
  echo "Warning: Using default UPTIME_KUMA_BASE_URL. Consider setting your own URL."; \
  fi

RUN if [ "$PAGE_ID" = "demo" ]; then \
  echo "Warning: Using default PAGE_ID 'demo'. Consider setting your own PAGE_ID."; \
  fi

COPY package.json bun.lock ./ 

RUN bun install --frozen-lockfile

COPY . .

RUN bun run build

# Runtime 阶段同理
FROM oven/bun:1.2-alpine
WORKDIR /app

ARG ALPINE_MIRROR=https://mirrors.aliyun.com
RUN sed -i "s|dl-cdn.alpinelinux.org|${ALPINE_MIRROR#https://}|g" /etc/apk/repositories \
    && apk update \
    && apk add --no-cache curl

ENV NPM_CONFIG_REGISTRY=https://registry.npmmirror.com

# 环境变量同上...

COPY --from=builder /app/.next/standalone/ ./ 
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/bun.lock ./bun.lock
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/config ./config
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/utils ./utils
COPY --from=builder /app/.next/static ./.next/static

EXPOSE ${PORT}

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:${PORT}/api/health || exit 1

CMD ["bun", "run", "start:docker"]

```

```env
UPTIME_KUMA_BASE_URL=https://xxx.xxx
PAGE_ID=xxx

FEATURE_EDIT_THIS_PAGE=false
FEATURE_SHOW_STAR_BUTTON=false

FEATURE_TITLE="xxx"
FEATURE_DESCRIPTION="A beautiful and modern uptime monitoring dashboard"
FEATURE_ICON="/icon.svg"

```
